### ISSUE TITLE
Vertical scroll for touch devices

### ISSUE THREAD

**Issue by Demitrius** [cthedot/vanillaSlider#1] opened 2018-02-17 09:15 UTC
Hello!

Not working vertical scrolling while touch starts from slider area.
Does it possible handle touch direction?

If slider horizontal, use horizontal touches for slide (left, right), and if touches are vertical, use default behavior (scroll page)

**Comment by cthedot** [comment] 2018-02-17 19:54
would you have an example for what you want? thanks!

**Comment by Demitrius** [comment] 2018-02-18 19:29
I have example what is not convenient for user experience.

Steps for reproduce.
1 - Open demo page http://cthedot.de/vanilla-slider/ with google chrome
2 - In Chrome console choose emulate device iPad
3 - Try to scroll down by touching page body
4 - Try to scroll down by touching slider body

Step 4 - No scrolling. Looks like touch move event stopped at slider.
This is not convenient. I say thanks if you can solve it.

**Comment by cthedot** [comment] 2018-02-24 13:36
hi,
this should not happen and just checked in Chrome 63 and then 64 (Win10 64).

If option "swipeaction: true" (which is the default too) is set a CSS "touch-action" is set to the relevant axis. On the example page this is normally horizontal swipe to navigate and scroll should be left untouched (or better should still work with touch ;-). 
On a vertical swipe example (2nd to last example with background images) this is explicitly set to be the other way round so vertical scroll is prevented as it does trigger slider navigation. 

There was the "touch-action: none" defined in the CSS which I removed as it probably prevented scrolling with touch if "swipeaction: false" was explicitly set. But as said the example did not.

There seemed to be glitch in Chrome 63 that in the last example on the page there was no scrolling possible at the top ~25% area of the images which I do not know why happened (seemerd to be caused by the preventing scroll example just above that which in a real world page is very unlikely to happen anyway). Below that area scrolling was possible though. Chrome just updated to now v64 and the problem is gone now.

Could you confirm or state more details of the problem?

**Closed as completed by cthedot** 2018-02-24 13:36 UTC
